import { FloatingYoutube } from "@/components/floating-youtube";
import { MediaProvider } from "@/components/media-context";
import { MediaControls } from "@/components/media-controls";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-900 text-white px-4 py-6">
          <MediaProvider>
            <div className="h-[calc(100vh-0rem)] overflow-y-auto">
              {children}
            </div>
          <MediaControls />
          <FloatingYoutube />
        </MediaProvider>
        </div>
      </body>
    </html>
  );
}
